import type { FnOStock } from "./types";

// Comprehensive NSE F&O stocks list with Upstox instrument keys
// These are the equity instrument keys used to fetch option chains
export const NSE_FO_STOCKS: FnOStock[] = [
  { symbol: "RELIANCE", instrumentKey: "NSE_EQ|INE002A01018", name: "Reliance Industries" },
  { symbol: "TCS", instrumentKey: "NSE_EQ|INE467B01029", name: "Tata Consultancy Services" },
  { symbol: "HDFCBANK", instrumentKey: "NSE_EQ|INE040A01034", name: "HDFC Bank" },
  { symbol: "INFY", instrumentKey: "NSE_EQ|INE009A01021", name: "Infosys" },
  { symbol: "ICICIBANK", instrumentKey: "NSE_EQ|INE090A01021", name: "ICICI Bank" },
  { symbol: "HINDUNILVR", instrumentKey: "NSE_EQ|INE030A01027", name: "Hindustan Unilever" },
  { symbol: "SBIN", instrumentKey: "NSE_EQ|INE062A01020", name: "State Bank of India" },
  { symbol: "BHARTIARTL", instrumentKey: "NSE_EQ|INE397D01024", name: "Bharti Airtel" },
  { symbol: "KOTAKBANK", instrumentKey: "NSE_EQ|INE237A01028", name: "Kotak Mahindra Bank" },
  { symbol: "ITC", instrumentKey: "NSE_EQ|INE154A01025", name: "ITC Limited" },
  { symbol: "LT", instrumentKey: "NSE_EQ|INE018A01030", name: "Larsen & Toubro" },
  { symbol: "AXISBANK", instrumentKey: "NSE_EQ|INE238A01034", name: "Axis Bank" },
  { symbol: "BAJFINANCE", instrumentKey: "NSE_EQ|INE296A01024", name: "Bajaj Finance" },
  { symbol: "MARUTI", instrumentKey: "NSE_EQ|INE585B01010", name: "Maruti Suzuki" },
  { symbol: "TATAMOTORS", instrumentKey: "NSE_EQ|INE155A01022", name: "Tata Motors" },
  { symbol: "SUNPHARMA", instrumentKey: "NSE_EQ|INE044A01036", name: "Sun Pharmaceutical" },
  { symbol: "TITAN", instrumentKey: "NSE_EQ|INE280A01028", name: "Titan Company" },
  { symbol: "ASIANPAINT", instrumentKey: "NSE_EQ|INE021A01026", name: "Asian Paints" },
  { symbol: "WIPRO", instrumentKey: "NSE_EQ|INE075A01022", name: "Wipro" },
  { symbol: "HCLTECH", instrumentKey: "NSE_EQ|INE860A01027", name: "HCL Technologies" },
  { symbol: "ULTRACEMCO", instrumentKey: "NSE_EQ|INE481G01011", name: "UltraTech Cement" },
  { symbol: "BAJAJFINSV", instrumentKey: "NSE_EQ|INE918I01018", name: "Bajaj Finserv" },
  { symbol: "ONGC", instrumentKey: "NSE_EQ|INE213A01029", name: "ONGC" },
  { symbol: "NTPC", instrumentKey: "NSE_EQ|INE733E01010", name: "NTPC" },
  { symbol: "TATASTEEL", instrumentKey: "NSE_EQ|INE081A01020", name: "Tata Steel" },
  { symbol: "POWERGRID", instrumentKey: "NSE_EQ|INE752E01010", name: "Power Grid Corp" },
  { symbol: "M&M", instrumentKey: "NSE_EQ|INE101A01026", name: "Mahindra & Mahindra" },
  { symbol: "JSWSTEEL", instrumentKey: "NSE_EQ|INE019A01038", name: "JSW Steel" },
  { symbol: "TECHM", instrumentKey: "NSE_EQ|INE669C01036", name: "Tech Mahindra" },
  { symbol: "ADANIENT", instrumentKey: "NSE_EQ|INE423A01024", name: "Adani Enterprises" },
  { symbol: "ADANIPORTS", instrumentKey: "NSE_EQ|INE742F01042", name: "Adani Ports" },
  { symbol: "COALINDIA", instrumentKey: "NSE_EQ|INE522F01014", name: "Coal India" },
  { symbol: "DRREDDY", instrumentKey: "NSE_EQ|INE089A01023", name: "Dr. Reddy's Labs" },
  { symbol: "CIPLA", instrumentKey: "NSE_EQ|INE059A01026", name: "Cipla" },
  { symbol: "BPCL", instrumentKey: "NSE_EQ|INE029A01011", name: "BPCL" },
  { symbol: "EICHERMOT", instrumentKey: "NSE_EQ|INE066A01021", name: "Eicher Motors" },
  { symbol: "HEROMOTOCO", instrumentKey: "NSE_EQ|INE158A01026", name: "Hero MotoCorp" },
  { symbol: "DIVISLAB", instrumentKey: "NSE_EQ|INE361B01024", name: "Divi's Laboratories" },
  { symbol: "GRASIM", instrumentKey: "NSE_EQ|INE047A01021", name: "Grasim Industries" },
  { symbol: "BRITANNIA", instrumentKey: "NSE_EQ|INE216A01030", name: "Britannia Industries" },
  { symbol: "NESTLEIND", instrumentKey: "NSE_EQ|INE239A01016", name: "Nestle India" },
  { symbol: "INDUSINDBK", instrumentKey: "NSE_EQ|INE095A01012", name: "IndusInd Bank" },
  { symbol: "APOLLOHOSP", instrumentKey: "NSE_EQ|INE437A01024", name: "Apollo Hospitals" },
  { symbol: "TATACONSUM", instrumentKey: "NSE_EQ|INE192A01025", name: "Tata Consumer" },
  { symbol: "SBILIFE", instrumentKey: "NSE_EQ|INE123W01016", name: "SBI Life Insurance" },
  { symbol: "HDFCLIFE", instrumentKey: "NSE_EQ|INE795G01014", name: "HDFC Life Insurance" },
  { symbol: "BAJAJ-AUTO", instrumentKey: "NSE_EQ|INE917I01010", name: "Bajaj Auto" },
  { symbol: "DABUR", instrumentKey: "NSE_EQ|INE016A01026", name: "Dabur India" },
  { symbol: "GODREJCP", instrumentKey: "NSE_EQ|INE102D01028", name: "Godrej Consumer" },
  { symbol: "PIDILITIND", instrumentKey: "NSE_EQ|INE318A01026", name: "Pidilite Industries" },
  { symbol: "HAVELLS", instrumentKey: "NSE_EQ|INE176B01034", name: "Havells India" },
  { symbol: "SIEMENS", instrumentKey: "NSE_EQ|INE003A01024", name: "Siemens" },
  { symbol: "INDUSTOWER", instrumentKey: "NSE_EQ|INE121J01017", name: "Indus Towers" },
  { symbol: "DLF", instrumentKey: "NSE_EQ|INE271C01023", name: "DLF Limited" },
  { symbol: "BANKBARODA", instrumentKey: "NSE_EQ|INE028A01039", name: "Bank of Baroda" },
  { symbol: "PNB", instrumentKey: "NSE_EQ|INE160A01022", name: "Punjab National Bank" },
  { symbol: "IDFCFIRSTB", instrumentKey: "NSE_EQ|INE092T01019", name: "IDFC First Bank" },
  { symbol: "FEDERALBNK", instrumentKey: "NSE_EQ|INE171A01029", name: "Federal Bank" },
  { symbol: "BEL", instrumentKey: "NSE_EQ|INE263A01024", name: "Bharat Electronics" },
  { symbol: "HAL", instrumentKey: "NSE_EQ|INE066F01020", name: "Hindustan Aeronautics" },
  { symbol: "BHEL", instrumentKey: "NSE_EQ|INE257A01026", name: "BHEL" },
  { symbol: "IOC", instrumentKey: "NSE_EQ|INE242A01010", name: "Indian Oil Corp" },
  { symbol: "GAIL", instrumentKey: "NSE_EQ|INE129A01019", name: "GAIL India" },
  { symbol: "VEDL", instrumentKey: "NSE_EQ|INE205A01025", name: "Vedanta Limited" },
  { symbol: "HINDALCO", instrumentKey: "NSE_EQ|INE038A01020", name: "Hindalco Industries" },
  { symbol: "TATAPOWER", instrumentKey: "NSE_EQ|INE245A01021", name: "Tata Power" },
  { symbol: "INDIGO", instrumentKey: "NSE_EQ|INE646L01027", name: "InterGlobe Aviation" },
  { symbol: "RECLTD", instrumentKey: "NSE_EQ|INE020B01018", name: "REC Limited" },
  { symbol: "PFC", instrumentKey: "NSE_EQ|INE134E01011", name: "Power Finance Corp" },
  { symbol: "CANBK", instrumentKey: "NSE_EQ|INE476A01014", name: "Canara Bank" },
  { symbol: "BANDHANBNK", instrumentKey: "NSE_EQ|INE545U01014", name: "Bandhan Bank" },
  { symbol: "LICHSGFIN", instrumentKey: "NSE_EQ|INE115A01026", name: "LIC Housing Finance" },
  { symbol: "MANAPPURAM", instrumentKey: "NSE_EQ|INE522D01027", name: "Manappuram Finance" },
  { symbol: "MUTHOOTFIN", instrumentKey: "NSE_EQ|INE414G01012", name: "Muthoot Finance" },
  { symbol: "VOLTAS", instrumentKey: "NSE_EQ|INE226A01021", name: "Voltas" },
  { symbol: "BIOCON", instrumentKey: "NSE_EQ|INE376G01013", name: "Biocon" },
  { symbol: "LUPIN", instrumentKey: "NSE_EQ|INE326A01037", name: "Lupin" },
  { symbol: "AUROPHARMA", instrumentKey: "NSE_EQ|INE406A01037", name: "Aurobindo Pharma" },
  { symbol: "TORNTPHARM", instrumentKey: "NSE_EQ|INE685A01028", name: "Torrent Pharma" },
  { symbol: "ZYDUSLIFE", instrumentKey: "NSE_EQ|INE010B01027", name: "Zydus Lifesciences" },
  { symbol: "ABCAPITAL", instrumentKey: "NSE_EQ|INE674K01013", name: "Aditya Birla Capital" },
  { symbol: "MFSL", instrumentKey: "NSE_EQ|INE766P01016", name: "Max Financial Services" },
  { symbol: "CHOLAFIN", instrumentKey: "NSE_EQ|INE121A01024", name: "Cholamandalam Investment" },
  { symbol: "SHRIRAMFIN", instrumentKey: "NSE_EQ|INE721A01013", name: "Shriram Finance" },
  { symbol: "ICICIPRULI", instrumentKey: "NSE_EQ|INE726G01019", name: "ICICI Prudential Life" },
  { symbol: "NAUKRI", instrumentKey: "NSE_EQ|INE663F01024", name: "Info Edge India" },
  { symbol: "TRENT", instrumentKey: "NSE_EQ|INE849A01020", name: "Trent Limited" },
  { symbol: "PAGEIND", instrumentKey: "NSE_EQ|INE761H01022", name: "Page Industries" },
  { symbol: "DIXON", instrumentKey: "NSE_EQ|INE935N01020", name: "Dixon Technologies" },
  { symbol: "POLYCAB", instrumentKey: "NSE_EQ|INE455K01017", name: "Polycab India" },
  { symbol: "PERSISTENT", instrumentKey: "NSE_EQ|INE262H01013", name: "Persistent Systems" },
  { symbol: "COFORGE", instrumentKey: "NSE_EQ|INE591G01017", name: "Coforge Limited" },
  { symbol: "LTIM", instrumentKey: "NSE_EQ|INE214T01019", name: "LTIMindtree" },
  { symbol: "MPHASIS", instrumentKey: "NSE_EQ|INE356A01018", name: "MphasiS Limited" },
  { symbol: "SAIL", instrumentKey: "NSE_EQ|INE114A01011", name: "Steel Authority" },
  { symbol: "NATIONALUM", instrumentKey: "NSE_EQ|INE139A01034", name: "National Aluminium" },
  { symbol: "NMDC", instrumentKey: "NSE_EQ|INE584A01023", name: "NMDC" },
  { symbol: "AMBUJACEM", instrumentKey: "NSE_EQ|INE079A01024", name: "Ambuja Cements" },
  { symbol: "ACC", instrumentKey: "NSE_EQ|INE012A01025", name: "ACC Limited" },
  { symbol: "SHREECEM", instrumentKey: "NSE_EQ|INE070A01015", name: "Shree Cement" },
  { symbol: "RAMCOCEM", instrumentKey: "NSE_EQ|INE331A01037", name: "Ramco Cements" },
  { symbol: "UPL", instrumentKey: "NSE_EQ|INE628A01036", name: "UPL Limited" },
  { symbol: "BALKRISIND", instrumentKey: "NSE_EQ|INE787D01026", name: "Balkrishna Industries" },
  { symbol: "MRF", instrumentKey: "NSE_EQ|INE883A01011", name: "MRF Limited" },
  { symbol: "MOTHERSON", instrumentKey: "NSE_EQ|INE775A01035", name: "Motherson Sumi" },
  { symbol: "ASHOKLEY", instrumentKey: "NSE_EQ|INE208A01029", name: "Ashok Leyland" },
  { symbol: "ESCORTS", instrumentKey: "NSE_EQ|INE042A01014", name: "Escorts Kubota" },
  { symbol: "TVSMOTOR", instrumentKey: "NSE_EQ|INE494B01023", name: "TVS Motor" },
  { symbol: "BOSCHLTD", instrumentKey: "NSE_EQ|INE323A01026", name: "Bosch Limited" },
  { symbol: "TATACHEM", instrumentKey: "NSE_EQ|INE092A01019", name: "Tata Chemicals" },
  { symbol: "DEEPAKNTR", instrumentKey: "NSE_EQ|INE288B01029", name: "Deepak Nitrite" },
  { symbol: "ATUL", instrumentKey: "NSE_EQ|INE100A01010", name: "Atul Limited" },
  { symbol: "PIIND", instrumentKey: "NSE_EQ|INE603J01030", name: "PI Industries" },
  { symbol: "SRF", instrumentKey: "NSE_EQ|INE647A01010", name: "SRF Limited" },
  { symbol: "PETRONET", instrumentKey: "NSE_EQ|INE347G01014", name: "Petronet LNG" },
  { symbol: "IGL", instrumentKey: "NSE_EQ|INE203G01027", name: "Indraprastha Gas" },
  { symbol: "MGL", instrumentKey: "NSE_EQ|INE002S01010", name: "Mahanagar Gas" },
  { symbol: "CONCOR", instrumentKey: "NSE_EQ|INE111A01025", name: "Container Corp" },
  { symbol: "IRCTC", instrumentKey: "NSE_EQ|INE335Y01020", name: "IRCTC" },
  { symbol: "IDEA", instrumentKey: "NSE_EQ|INE669E01016", name: "Vodafone Idea" },
  { symbol: "ZEEL", instrumentKey: "NSE_EQ|INE256A01028", name: "Zee Entertainment" },
  { symbol: "PVR", instrumentKey: "NSE_EQ|INE191H01014", name: "PVR INOX" },
  { symbol: "BERGEPAINT", instrumentKey: "NSE_EQ|INE463A01038", name: "Berger Paints" },
  { symbol: "COLPAL", instrumentKey: "NSE_EQ|INE259A01022", name: "Colgate-Palmolive" },
  { symbol: "MARICO", instrumentKey: "NSE_EQ|INE196A01026", name: "Marico Limited" },
  { symbol: "JUBLFOOD", instrumentKey: "NSE_EQ|INE797F01020", name: "Jubilant FoodWorks" },
  { symbol: "OFSS", instrumentKey: "NSE_EQ|INE881D01027", name: "Oracle Financial" },
  { symbol: "LALPATHLAB", instrumentKey: "NSE_EQ|INE600L01024", name: "Dr. Lal PathLabs" },
  { symbol: "METROPOLIS", instrumentKey: "NSE_EQ|INE112L01020", name: "Metropolis Healthcare" },
  { symbol: "GMRINFRA", instrumentKey: "NSE_EQ|INE776C01039", name: "GMR Airports" },
  { symbol: "IRFC", instrumentKey: "NSE_EQ|INE053F01010", name: "IRFC" },
  { symbol: "NHPC", instrumentKey: "NSE_EQ|INE848E01016", name: "NHPC" },
  { symbol: "SJVN", instrumentKey: "NSE_EQ|INE002L01015", name: "SJVN" },
  { symbol: "ADANIGREEN", instrumentKey: "NSE_EQ|INE364U01010", name: "Adani Green Energy" },
  { symbol: "ADANIPOWER", instrumentKey: "NSE_EQ|INE814H01011", name: "Adani Power" },
  { symbol: "JSWENERGY", instrumentKey: "NSE_EQ|INE121E01018", name: "JSW Energy" },
  { symbol: "TORNTPOWER", instrumentKey: "NSE_EQ|INE813H01021", name: "Torrent Power" },
  { symbol: "CUMMINSIND", instrumentKey: "NSE_EQ|INE298A01020", name: "Cummins India" },
  { symbol: "ABB", instrumentKey: "NSE_EQ|INE117A01022", name: "ABB India" },
  { symbol: "CGPOWER", instrumentKey: "NSE_EQ|INE067A01029", name: "CG Power" },
  { symbol: "HINDPETRO", instrumentKey: "NSE_EQ|INE094A01015", name: "HPCL" },
  { symbol: "OBEROIRLTY", instrumentKey: "NSE_EQ|INE093I01010", name: "Oberoi Realty" },
  { symbol: "GODREJPROP", instrumentKey: "NSE_EQ|INE484J01027", name: "Godrej Properties" },
  { symbol: "PRESTIGE", instrumentKey: "NSE_EQ|INE811K01011", name: "Prestige Estates" },
  { symbol: "PHOENIXLTD", instrumentKey: "NSE_EQ|INE211B01039", name: "Phoenix Mills" },
  { symbol: "LTTS", instrumentKey: "NSE_EQ|INE010V01017", name: "L&T Technology" },
  { symbol: "EXIDEIND", instrumentKey: "NSE_EQ|INE302A01020", name: "Exide Industries" },
  { symbol: "AMARAJABAT", instrumentKey: "NSE_EQ|INE885A01032", name: "Amara Raja Energy" },
  { symbol: "MAXHEALTH", instrumentKey: "NSE_EQ|INE027H01010", name: "Max Healthcare" },
  { symbol: "LAURUSLABS", instrumentKey: "NSE_EQ|INE947Q01028", name: "Laurus Labs" },
  { symbol: "SYNGENE", instrumentKey: "NSE_EQ|INE398R01022", name: "Syngene International" },
  { symbol: "IPCALAB", instrumentKey: "NSE_EQ|INE571A01020", name: "IPCA Laboratories" },
  { symbol: "GRANULES", instrumentKey: "NSE_EQ|INE101D01020", name: "Granules India" },
  { symbol: "MCX", instrumentKey: "NSE_EQ|INE745G01035", name: "Multi Commodity Exchange" },
  { symbol: "CANFINHOME", instrumentKey: "NSE_EQ|INE477A01020", name: "Can Fin Homes" },
  { symbol: "ICICIGI", instrumentKey: "NSE_EQ|INE765G01017", name: "ICICI Lombard" },
  { symbol: "SBICARD", instrumentKey: "NSE_EQ|INE018E01016", name: "SBI Cards" },
  { symbol: "AUBANK", instrumentKey: "NSE_EQ|INE949L01017", name: "AU Small Finance Bank" },
  { symbol: "ASTRAL", instrumentKey: "NSE_EQ|INE006I01046", name: "Astral Limited" },
  { symbol: "SUPREMEIND", instrumentKey: "NSE_EQ|INE195A01028", name: "Supreme Industries" },
  { symbol: "CROMPTON", instrumentKey: "NSE_EQ|INE299U01018", name: "Crompton Greaves" },
  { symbol: "BATAINDIA", instrumentKey: "NSE_EQ|INE176A01028", name: "Bata India" },
  { symbol: "DALBHARAT", instrumentKey: "NSE_EQ|INE439HO1020", name: "Dalmia Bharat" },
  { symbol: "NAVINFLUOR", instrumentKey: "NSE_EQ|INE048G01026", name: "Navin Fluorine" },
  { symbol: "COROMANDEL", instrumentKey: "NSE_EQ|INE169A01031", name: "Coromandel International" },
  { symbol: "GNFC", instrumentKey: "NSE_EQ|INE113A01013", name: "GNFC" },
  { symbol: "CHAMBLFERT", instrumentKey: "NSE_EQ|INE085A01013", name: "Chambal Fertilizers" },
  { symbol: "ABFRL", instrumentKey: "NSE_EQ|INE647O01011", name: "Aditya Birla Fashion" },
  { symbol: "CUB", instrumentKey: "NSE_EQ|INE491A01021", name: "City Union Bank" },
];

// Get all instrument keys as comma-separated string for batch API calls
export function getInstrumentKeysChunk(stocks: FnOStock[], chunkSize: number = 50): string[][] {
  const chunks: string[][] = [];
  for (let i = 0; i < stocks.length; i += chunkSize) {
    chunks.push(stocks.slice(i, i + chunkSize).map((s) => s.instrumentKey));
  }
  return chunks;
}

export function getStockBySymbol(symbol: string): FnOStock | undefined {
  return NSE_FO_STOCKS.find((s) => s.symbol === symbol);
}

export function getStockByKey(key: string): FnOStock | undefined {
  return NSE_FO_STOCKS.find((s) => s.instrumentKey === key);
}
